/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Picture/': RouteRecordInfo<'/Picture/', '/Picture', Record<never, never>, Record<never, never>>,
    '/Picture/AlphaCoders': RouteRecordInfo<'/Picture/AlphaCoders', '/Picture/AlphaCoders', Record<never, never>, Record<never, never>>,
    '/Picture/Desktop': RouteRecordInfo<'/Picture/Desktop', '/Picture/Desktop', Record<never, never>, Record<never, never>>,
    '/Picture/Meme': RouteRecordInfo<'/Picture/Meme', '/Picture/Meme', Record<never, never>, Record<never, never>>,
    '/Picture/Mobile': RouteRecordInfo<'/Picture/Mobile', '/Picture/Mobile', Record<never, never>, Record<never, never>>,
    '/Picture/Space': RouteRecordInfo<'/Picture/Space', '/Picture/Space', Record<never, never>, Record<never, never>>,
  }
}
