/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMenuDesktop: typeof import('./components/AppMenuDesktop.vue')['default']
    AppMenuMobile: typeof import('./components/AppMenuMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WallpaperGrid: typeof import('./components/WallpaperGrid.vue')['default']
  }
}
