/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAnnouncement: typeof import('./components/AppAnnouncement.vue')['default']
    AppBars: typeof import('./components/AppBars.vue')['default']
    AppLove: typeof import('./components/AppLove.vue')['default']
    AppNav: typeof import('./components/AppNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WallpaperGrid: typeof import('./components/WallpaperGrid.vue')['default']
  }
}
